#!/bin/bash
#!/bin/bash
#SBATCH -p std
#SBATCH --time=10:00:00
#SBATCH -N 1
#SBATCH --ntasks=5
#SBATCH --cpus-per-task=1
#SBATCH --mem=128000
#SBATCH --job-name=MGD-batch

source /mnt/petaStor/valadao/C-DM-lagr/envao/bin/activate

export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export BLIS_NUM_THREADS=1

# bash paral.sh
bash zip_paral.sh
# python3 run_mgd.py 1 250 1 dataset.npz mom1.txt












# SBATCH -p std
# SBATCH -p deepflow
# SBATCH --time 00:10:00      # format: HH:MM:SS
# SBATCH -N 1                 # xxx node
# SBATCH --ntasks-per-node=88  # xxx core per node
# SBATCH --mem=32000           # memory per node out of xxx MB
# SBATCH --job-name=MGD-vitu-gauss
# SBATCH --ntasks=1
# SBATCH --cpus-per-task=8

# SBATCH -w a100-2           # ask for specific host
# SBATCH --gres=gpu:a100:1   # xxx gpus per node
# SBATCH --mail-type=ALL
# SBATCH --mail-user=<user_email>

# module purge
# module load mpi/latest
# source /mnt/petaStor/valadao/C-DM-lagr/envao/bin/activate
# source /mnt/petaStor/valadao/venv_deepflow/bin/activate


# python3 run_mgd.py "$sigma" "$Nt" "$seed" "$data_path" "$moms_path" "$solve_bool"
# python3 generate_dataset_bur.py 256 512 256 0.001 1 1 1 1
# python3 generate_dataset_fbm.py 256 512 0.25 1 3.14159 1
# python3 generate_dataset_gss.py 256 512 1 0.5 1

# python3 run_mgd_pool.py 1 100 1 dataset.npz mom1.txt True 1
# python3 -m cProfile -s tottime run_mgd.py 1 100 1 dataset.npz mom1.txt True

# python3 run_mgd.py 1 250 1 dataset.npz mom1.txt

# bash paral.sh
